const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});

const data = [
  {
    category: { name: 'Deep Questions', color: '8E44AD' },
    questions: [
      'What is a belief you hold with which many people disagree?',
      "What's something you're still trying to prove to yourself?",
      "What's the most important lesson you've learned from a failure?",
      'If you could live your life over again, what would you change?',
      'What does it mean to live a good life?',
      "What is a fear you have that you're trying to overcome?",
      "What is a dream you've let go of?",
      "What is the biggest risk you've ever taken?",
      'What is something you wish you were better at?',
      "What is a memory you'll cherish forever?",
      'What is a quality you admire most in others?',
      'What is a book or movie that changed your perspective on life?',
      "What is something you're grateful for today?",
      "What is a cause you're passionate about?",
      "What is a piece of advice you'd give to your younger self?",
      'What is a time you felt truly alive?',
      "What is a question you're still searching for the answer to?",
      'What is a legacy you want to leave behind?',
      'What is the meaning of your life?',
      "What is something you've never told anyone?",
      'When have you felt most at peace with your choices?',
      'What truth are you still wrestling with?',
      'How do you measure personal growth for yourself?',
      'What would you sacrifice for your deepest values?',
      'Which part of your identity are you still discovering?',
      'Which past decision shaped you the most dramatically?',
      'How do you stay hopeful during long setbacks?',
      'What question would you ask your future self in 10 years?',
      'What legacy do you hope to leave your community specifically?',
      'How do you balance ambition with contentment in daily life?',
    ],
  },
  {
    category: { name: 'Faith & Beliefs', color: '3498DB' },
    questions: [
      'If love is real do you think it points to something bigger than biology?',
      'Do you believe in a higher power? Why or why not?',
      'What role does spirituality play in your life?',
      'What are your thoughts on fate and free will?',
      "Do you believe in an afterlife? What do you think it's like?",
      'What is a spiritual practice you find meaningful?',
      'How do you find peace in a chaotic world?',
      'What is a moral principle you live by?',
      'What is a time you felt a deep connection to the universe?',
      'How has your understanding of faith evolved over time?',
      'What is a question you have for a divine being?',
      'What gives you hope?',
      'Do you believe in miracles? Have you ever experienced one?',
      'What is the role of forgiveness in your life?',
      'How do you deal with doubt?',
      'What is a sacred text or story that inspires you?',
      'What does it mean to be a good person?',
      'What is your purpose in life, from a spiritual perspective?',
      'How do you connect with your inner self?',
      'What is a spiritual goal you are working towards?',
      'What does the resurrection of Jesus mean to you personally?',
      'How do you practice daily prayer or devotion time?',
      'Which Bible verse encourages you during difficult seasons?',
      'How has your church community shaped your walk with Christ?',
      'What does grace mean in your life right now?',
      "How do you discern God's guidance when making decisions?",
      'How do you share your faith with others in a loving way?',
      'In what ways do you see the Holy Spirit at work around you?',
      'What spiritual discipline would you like to grow in this year?',
      'How do you hold onto faith when facing unanswered prayers?',
    ],
  },
  {
    category: { name: 'Silly Questions', color: '2ECC71' },
    questions: [
      'If animals could talk, which would be the rudest?',
      'What is the silliest thing you have ever done?',
      'If you were a vegetable, what vegetable would you be?',
      'What is a weird food combination you love?',
      'If you could have any superpower, but it had to be useless, what would it be?',
      'What is the most embarrassing song you know by heart?',
      'If you had to be a cartoon character for a week, who would you be?',
      'What is a ridiculous fact you know?',
      'If you could only eat one food for the rest of your life, what would it be?',
      'What is the funniest joke you know?',
      'If you could replace your hands with any object, what would you choose?',
      'What is a weird habit you have?',
      'If you could talk to one species of animal, which would it be?',
      'What is the most ridiculous purchase you have ever made?',
      'If you were a ghost, who would you haunt and why?',
      'What is a funny memory from your childhood?',
      'If you could have a theme song that played every time you entered a room, what would it be?',
      'What is the weirdest dream you have ever had?',
      'If you could be any mythical creature, what would you be?',
      'What is a silly fear you have?',
      'If you could invent a holiday, what ridiculous traditions would it have?',
      'What would be the worst theme for a theme park?',
      'If you were a kitchen appliance, which one would you be and why?',
      'What cheesy movie quote do you secretly love?',
      'If you had a pet dragon, what would you name it?',
      'What is the weirdest thing you would do for five dollars?',
      "If laughter is the best medicine, what's your prescription?",
      'What snack would you smuggle into a movie theater?',
      'If your life had a laugh track, when would it play the loudest?',
      'What would be the title of your autobiography if it were a comedy?',
    ],
  },
  {
    category: { name: 'Personal Growth', color: 'F39C12' },
    questions: [
      'What is a new skill you would like to learn?',
      'What is a habit you are trying to build or break?',
      'What is a book that has had a significant impact on you?',
      'What is a challenge you have overcome that made you stronger?',
      'What is a fear that is holding you back?',
      'What is something you are proud of accomplishing?',
      'What is a way you can step out of your comfort zone this week?',
      'What is a piece of feedback you received that was hard to hear but helpful?',
      'What is a long-term goal you are working towards?',
      'How do you practice self-care?',
      'What is a mistake you have learned from?',
      'What is a quality you want to develop in yourself?',
      'What is a way you can be more mindful in your daily life?',
      'What is a person who inspires you to be better?',
      'What is a limiting belief you are trying to let go of?',
      'How do you define success for yourself?',
      'What is a way you can contribute to your community?',
      'What is a passion you would like to pursue?',
      'What is a way you can be more creative?',
      'What is a lesson you have learned about happiness?',
      'What small habit could have the biggest positive impact for you?',
      'How do you respond when progress feels invisible?',
      'Who is someone you can ask for honest accountability?',
      'What does rest look like when you are at your best?',
      'How do you celebrate reaching a milestone?',
      'What is a creative outlet you would like to explore?',
      'How do you keep learning when you feel stuck?',
      'What values guide your long-term decisions?',
      'How do you recharge after a demanding day?',
      'What would future you thank you for starting today?',
    ],
  },
  {
    category: { name: 'Relationships', color: 'E74C3C' },
    questions: [
      'What is a quality you value most in a friend?',
      'What is a way you show love and appreciation to others?',
      'What is a memory of a time a friend was there for you?',
      'What is a lesson you have learned about love?',
      'How do you handle conflict in a relationship?',
      'What is a way you can be a better friend or partner?',
      'What is a relationship that has taught you a lot?',
      'What is a boundary you have set in a relationship?',
      'What is a way you can strengthen your connection with your family?',
      'What is a time you felt truly understood by someone?',
      'What is a quality you look for in a romantic partner?',
      'How do you maintain long-distance friendships?',
      'What is a piece of advice you would give to someone about relationships?',
      'What is a way you can be more present with the people you care about?',
      'What is a challenge you have faced in a relationship and how did you overcome it?',
      'What is a way you can show more empathy to others?',
      'What is a sign of a healthy relationship?',
      'What is a way you can forgive someone who has hurt you?',
      'What is a way you can be more vulnerable in your relationships?',
      'What is a relationship you are grateful for?',
      'How do you express appreciation in small everyday ways?',
      'What tradition would you like to start with people you love?',
      'How do you rebuild trust after it has been broken?',
      'What boundaries help you feel safe in relationships?',
      'How do you support friends when they are grieving?',
      'What role does humor play in your relationships?',
      'How do you stay connected during busy seasons?',
      'What do you need to feel heard in a conversation?',
      'How do you navigate differences in values with someone close?',
      'What is something you admire about your family culture?',
      'What does a supportive partnership look like to you?',
      'How do you like to celebrate relationship milestones?',
      'How do you communicate when you need space?',
      'What habits help you stay close with family members?',
      'How do you nurture friendships when you live far apart?',
      'What boundaries are non-negotiable for you in romance?',
      'When do you feel most appreciated by someone you love?',
      'How do you express care without using words?',
      'What is your favorite memory with a sibling or cousin?',
      'How do you handle differing expectations in a relationship?',
      'What shared activity brings you closer to people?',
      'How do you respond when someone you love is stressed?',
      'What do you believe keeps long-term relationships thriving?',
      'How do you check in on your friends emotionally?',
      'What questions do you ask to deepen a connection?',
      'How do you show up for loved ones on their hard days?',
      'What does forgiveness look like in practice for you?',
      'How do you keep romance alive in everyday life?',
      'What relationship lessons did you learn from your parents?',
      'How do you handle jealousy when it arises?',
      'What role does honesty play in your closest relationships?',
      'How do you share feedback with someone you care about?',
      'What routines help you feel connected at home?',
      'How do you support a partner chasing a big goal?',
      'What makes you feel emotionally secure with someone?',
      'How do you balance family traditions with new ones?',
      'What is your favorite way to spend quality time together?',
      'How do you approach finances in a partnership?',
      'What do you appreciate most about your closest friend?',
      'How do you handle mismatched social energy with loved ones?',
      'What role do shared values play in your relationships?',
      'How do you talk about the future with someone you love?',
      'What boundaries help you maintain healthy friendships?',
      'How do you support a loved one through change?',
      'What is your love language and how do you express it?',
      'How do you celebrate the wins of people you care about?',
      'What do you enjoy learning from your partner or friends?',
      'How do you handle conflict when emotions are high?',
      'What makes you feel trusted in a relationship?',
      'How do you reset after an argument?',
      'How do you use humor to lighten tough moments together?',
      'What boundaries help you protect your personal time?',
      'How do you introduce someone new to your circle of friends?',
      'What is your approach to sharing household responsibilities?',
      'How do you navigate holidays with different families?',
      'What is your favorite tradition to share with a partner?',
      'How do you express gratitude in long-term relationships?',
      'What kind of surprise gestures do you enjoy giving?',
      'How do you talk about dreams and goals with loved ones?',
      'What helps you feel seen and understood by someone?',
      'How do you encourage growth in the people you love?',
      'What boundaries do you set with technology when together?',
      'How do you divide decision-making in a partnership?',
      'What do you consider a red flag in a relationship?',
      'How do you support friends during major life transitions?',
      'What qualities make you feel safe opening up?',
      'How do you keep inside jokes alive over time?',
      'What is your favorite way to reconnect after time apart?',
      'How do you manage expectations with loved ones?',
      'What role does vulnerability play in your friendships?',
      'How do you like to mark anniversaries or milestones?',
      'What helps you rebuild closeness after conflict?',
      'How do you encourage honesty in your relationships?',
      'What boundaries help you maintain healthy digital communication?',
      'How do you talk about personal growth with a partner?',
      'What do you admire about strong couples you know?',
      'How do you support a loved one\'s mental health?',
      'What shared goals strengthen your relationships?',
      'How do you balance spontaneous plans with commitments?',
      'What promises feel most meaningful to you?',
    ],
  },
  {
    category: { name: 'Simple', color: '1ABC9C' },
    questions: [
      'What brought you to this city?',
      'How do you usually like to spend your weekends?',
      'Are you more of a morning person or a night owl?',
      'What type of music do you find yourself playing on repeat?',
      'Do you prefer coffee, tea, or something else to start your day?',
      'Which movie can you watch over and over without getting bored?',
      'Have you picked up any hobbies recently?',
      'What book or podcast are you into right now?',
      'What is your go-to comfort food?',
      'Do you have a favorite vacation spot or dream destination?',
      'What kind of activities help you unwind after a long day?',
      'Are you more spontaneous or a planner?',
      'What is a small thing that instantly makes your day better?',
      'Do you enjoy cooking, and if so, what do you like to make?',
      'What was the best part of your week?',
      'Do you have any pets, or did you grow up with any?',
      'What is a story your friends love hearing you tell?',
      'What show are you currently watching?',
      'If you could learn any skill instantly, what would it be?',
      'What is your favorite way to stay active?',
      'Do you like trying new restaurants or sticking to your favorites?',
      'What is a hidden gem in this city that you recommend?',
      'Are you into board games or card games?',
      'What song always gets you dancing?',
      'What is the best advice you have ever received?',
      'Do you have a favorite seasonal tradition?',
      'What kind of art or creative outlets do you enjoy?',
      'How do you like to celebrate your birthday?',
      'What is one small goal you are working on this year?',
      'What makes you laugh the most?',
      'Do you consider yourself more of an introvert or extrovert?',
      'What was your favorite cartoon growing up?',
      'What’s your favorite way to celebrate when something good happens?',
      'Do you enjoy road trips, or do you prefer flying?',
      'Which app on your phone do you open the most?',
      'What food could you eat every day and never get tired of?',
      'What’s your favorite season and why?',
      'Are you more into podcasts or audiobooks lately?',
      'What does your ideal Sunday look like?',
      'What’s your favorite dessert?',
      'Is there a sport you love to watch or play?',
      'Do you like going to concerts or live events?',
      'What’s a small act of kindness you still remember?',
      'What was the last thing that made you smile today?',
      'How do you feel about surprises?',
      'What’s one thing you always pack when you travel?',
      'Do you have a favorite quote or mantra?',
      'What’s your go-to karaoke song?',
      'Is there a language you’d love to learn?',
      'What’s your favorite way to get some fresh air?',
      'Do you remember your first job? What was it?',
      'What type of cuisine do you get most excited about?',
      'How do you stay motivated on tough days?',
      'Are you into puzzles or brain games?',
      'What’s your favorite thing about your hometown?',
      'Do you collect anything?',
      'What’s the best compliment you’ve ever received?',
      'Which movie genre do you reach for most often?',
      'Do you like visiting museums or galleries?',
      'What’s something on your bucket list this year?',
      'Do you enjoy trying new workouts or fitness classes?',
      'What’s your favorite way to give back to your community?',
      'Is there a skill you learned as a kid that you still use?',
      'What song always helps you relax?',
      'Do you enjoy planning parties or events?',
      'What local restaurant do you recommend to everyone?',
      'Do you have a favorite childhood memory?',
      'How do you usually get around the city?',
      'Are you more drawn to the mountains or the beach?',
      'What’s your favorite ice cream flavor?',
      'Do you like attending festivals or fairs?',
      'What’s your go-to conversation starter?',
      'What was the last book you couldn’t put down?',
      'Do you have a morning routine or do you go with the flow?',
      'What’s your favorite boardwalk or waterfront to visit?',
      'Do you enjoy game nights with friends?',
      'What’s your favorite memory from the past year?',
      'What’s a small luxury you treat yourself to?',
      'Do you enjoy caring for plants or gardening?',
      'What’s one city you’d love to live in for a month?',
    ],
  },
];

const insertData = async () => {
  const client = await pool.connect();
  try {
    for (const item of data) {
      const res = await client.query(
        'INSERT INTO categories (name, color) VALUES ($1, $2) ON CONFLICT (name) DO UPDATE SET color = EXCLUDED.color RETURNING id',
        [item.category.name, item.category.color]
      );
      const categoryId = res.rows[0].id;

      for (const question of item.questions) {
        await client.query(
          'INSERT INTO questions (text, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING',
          [question, categoryId]
        );
      }
    }

    console.log('Data inserted successfully.');
  } catch (err) {
    console.error('Error inserting data:', err);
  } finally {
    client.release();
  }
};

insertData()
  .then(() => {
    console.log('Data insertion complete.');
  })
  .finally(() => {
    pool.end();
  });